# Manually:
#   $ fly scale count 1
#   $ fly volumes create tsgo_data --region ord --size 1
#   $ fly secrets set TS_AUTHKEY=....

app = "tsgo"

[build]
image = "registry.fly.io/tsgo:latest"

[deploy]
strategy = "immediate"

[mounts]
source="tsgo_data"
destination="/root"
